name: Variables
run-name: Run by @${{ github.actor }}
on: push
jobs:
  print:
    name: Super Useful Job
    # if: ${{ github.actor=='octocat'}}
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }} # Variablesの参照
      PASSWORD: ${{ secrets.PASSWORD }}
      LITERAL_NULL: ${{ null }} # null型
      LITERAL_BOOLEAN: ${{ true }} # boolean型
      LITERAL_NUMBER: ${{ 1234 }} # number型
      LITERAL_STRING: ${{ 'Hello' }} # string型（通常記法）
      LITERAL_OMIT_STRING: World # string型（省略記法）
      CONTAINS_FUNC: ${{ contains('Hello', 'ell') }} # 「ell」を含むか
      STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # 「He」で始まるか
      ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }} # 「lo」で終わるか
      FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }} # フォーマット
      JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} # カンマで結合
      CONTEXT: ${{ toJSON(github) }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
      - run: printenv | grep 'LITERAL_'
      - run: printenv | grep '_FUNC'
      - run: echo "${CONTEXT}"
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '100') }}
      - name: Amazing Script
        run: echo "Hello"
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照
        run: echo "${RESULT}"
      - run: echo "RESULT2=Hello2" >> "${GITHUB_ENV}"
      - run: echo "${RESULT2}"
      - run: echo "::debug::This is a debug log"
      - run: |
          set -x
          date
          hostname
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
      - run: echo "::add-mask::${PASSWORD}"
      - run: echo "${PASSWORD}"
      - run: echo "::error::This is an error" # Errorレベルのアノテーション
      - run: echo "::warning::This is a warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is a notice" # Noticeレベルのアノテーション
      - run: | # マークダウンテキストをジョブサマリーへ出力
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job"
